# Auto-generated by compose2nix.

{
  lib,
  writeShellApplication,
  docker,
  docker-compose,
  bash,
  nginxPort ? "85",
  nginxTLSPort ? "445",
  ...
}:

let
  nginxConfig = lib.fileset.toSource {
    root = ./.;
    fileset = ./nginx;
  };
  dockerComposeFile = lib.fileset.toSource {
    root = ./.;
    fileset = ./docker-compose.yml;
  };
  env = lib.fileset.toSource {
    root = ./.;
    fileset = ./deploy.env;
  };
in

writeShellApplication rec {
  name = "appflowy";
  text = ''
    PROJECT="${name}"
    VERBOSE="false"
    CMD="start"
    DOCKER_COMPOSE=${dockerComposeFile}/docker-compose.yml
    ENV_FILE=${env}/deploy.env

    usage() {
    	echo "Usage: $0 [OPTIONS] <CMD>"
    	echo
    	echo "Options:"
    	echo "  -v, --verbose    Enable verbose output"
    	echo
    	echo "CMD:"
    	echo "  -h, --help    Show this help message and exit"
    	exit 1
    }

    start() {
    	docker compose -p $PROJECT -f $DOCKER_COMPOSE --env-file $ENV_FILE up
    }

    stop() {
    	docker compose -p $PROJECT -f $DOCKER_COMPOSE --env-file $ENV_FILE down
    }

    if [[ $# -eq 0 ]]; then
    	usage
    fi

    while [[ $# -gt 0 ]]; do
    	case "$1" in
    	-h | --help)
    		CMD="help"
    		break
    		;;
    	-v | --verbose)
    		VERBOSE=true
    		set -x
    		shift
    		;;
    	*)
    		CMD=$1
    		shift
    		;;
    	esac
    done

    if [[ "$CMD" == "start" ]]; then
    	if [[ $VERBOSE == "true" ]]; then
    		echo "Starting projet $PROJECT"
    	fi
    	start
    elif [[ "$CMD" == "stop" ]]; then
    	if [[ $VERBOSE == "true" ]]; then
    		echo "Stopping projet $PROJECT"
    	fi
    	stop
    elif [[ "$CMD" == "help" ]]; then
    	usage
    fi
  '';
  runtimeEnv = {
    NGINX_CONFIG_DIR = "${nginxConfig}/nginx";
    NGINX_PORT = "${nginxPort}";
    NGINX_TLS_PORT = "${nginxTLSPort}";
  };
  runtimeInputs = [
    docker
    bash
    docker-compose
  ];
  excludeShellChecks = [ ];
}
