#! /usr/bin/env bash
NIXOS_CONF=${1:?"Specify the Host/Specialization"}

nix --extra-experimental-features nix-command --extra-experimental-features flakes run github:nix-community/nh -- os switch . -H "$NIXOS_CONF" "$@"
